# Ablation Study Configuration for FRF Model
# Dataset config
field_separator: "\t"
USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
TIME_FIELD: timestamp

# Field type settings
load_col:
  inter: [user_id, item_id, timestamp]

# Sequential recommendation settings
MAX_ITEM_LIST_LENGTH: 100          
ITEM_LIST_LENGTH_FIELD: item_length   

# Model config
embedding_size: 128
hidden_size: 128
n_layers: 2
n_heads: 2
inner_size: 256
hidden_dropout_prob: 0.3
attn_dropout_prob: 0.3
learning_rate: 0.001 
weight_decay: 0.0001 
hidden_act: 'gelu'
layer_norm_eps: 1e-12
initializer_range: 0.02
loss_type: 'BPR'  

# FRF-specific parameters
cutoff_ratio: 0.65              # High-low frequency split ratio
rep_weight: 0.75                # Base repetition weight
high_freq_scale: 1.8            # High frequency enhancement factor
window_size: 7                  # DTW window size
rep_threshold: 0.6              # Repetition detection threshold
contrast_weight: 0.25           # Contrastive learning weight

# Training enhancement parameters
label_smoothing: 0.1            # Label smoothing factor
temperature: 0.07               # Temperature for contrastive learning
freq_reg_weight: 0.01           # Frequency domain regularization weight

# Negative sampling config (for BPR loss)
train_neg_sample_args:
  distribution: uniform
  sample_num: 1

# Evaluation settings
eval_setting: TO_LS,full 
metrics: ["Recall", "MRR", "NDCG", "Hit", "Precision"] 
topk: [10, 20]
valid_metric: MRR@10
use_amp: True

# Training settings
learner: adam
epochs: 30                      # Increased for ablation study
train_batch_size: 2048          # Reduced for stability
eval_batch_size: 2048
stopping_step: 10
eval_step: 1

# Reproducibility
seed: 2024
state: INFO